# Generated by Django 3.2.25 on 2026-01-12 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RotaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('publish_version', models.PositiveIntegerField(default=0)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_rotadays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('OPERATIVE', 'Production Operative'), ('SUPERVISOR', 'Production Supervisor')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='rota.crew')),
            ],
            options={
                'ordering': ['crew__sort_order', 'crew__name', 'first_name', 'last_name'],
                'permissions': [('rota_manager', 'Can manage rota (create/update/delete)'), ('rota_viewer', 'Can view rota')],
            },
        ),
        migrations.CreateModel(
            name='RotaDayAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ASSIGNMENT_CREATED', 'Assignment created'), ('ASSIGNMENT_UPDATED', 'Assignment updated'), ('ASSIGNMENT_DELETED', 'Assignment deleted'), ('PUBLISHED', 'Published'), ('REPUBLISHED', 'Republished')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=255)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rota_audit_events', to=settings.AUTH_USER_MODEL)),
                ('rotaday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='rota.rotaday')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Isolator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('clean_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolators', to='rota.cleanroom')),
            ],
            options={
                'ordering': ['clean_room__number', 'order'],
                'unique_together': {('clean_room', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('ROOM', 'Room (Supervisor)'), ('ISOLATOR', 'Isolator (Operative/Supervisor)')], max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_room_supervisor', models.BooleanField(default=False)),
                ('clean_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rota.cleanroom')),
                ('isolator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rota.isolator')),
                ('rotaday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rota.rotaday')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rota.shifttemplate')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rota.staffmember')),
            ],
            options={
                'unique_together': {('rotaday', 'staff')},
            },
        ),
    ]
