# Generated by Django 5.2.8 on 2025-11-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RotaDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Isolator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('clean_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isolators', to='rota.cleanroom')),
            ],
            options={
                'ordering': ['clean_room__number', 'order'],
                'unique_together': {('clean_room', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('OPERATIVE', 'Production Operative'), ('SUPERVISOR', 'Production Supervisor')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='rota.crew')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('ROOM', 'Room (Supervisor)'), ('ISOLATOR', 'Isolator (Operative)')], max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('clean_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rota.cleanroom')),
                ('isolator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rota.isolator')),
                ('rotaday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rota.rotaday')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rota.shifttemplate')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rota.staffmember')),
            ],
            options={
                'unique_together': {('rotaday', 'staff', 'clean_room', 'isolator', 'shift')},
            },
        ),
    ]
