# Generated by Django 3.2.25 on 2026-02-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='shift_block',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], db_index=True, default='AM', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('rotaday', 'staff', 'shift_block'), name='uniq_staff_per_rotaday_shiftblock'),
        ),
    ]
