# Generated by Django 3.2.25 on 2025-11-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'permissions': [('manage_rota', 'Can create and edit rota')]},
        ),
    ]
