# Generated by Django 3.2.25 on 2026-02-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0002_auto_20260216_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rota.shifttemplate'),
        ),
    ]
