# Generated by Django 3.2.25 on 2025-11-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0002_alter_assignment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staffmember',
            options={'permissions': [('rota_manager', 'Can manage rota (create/update/delete)'), ('rota_viewer', 'Can view rota')]},
        ),
    ]
