# Generated by Django 3.2.25 on 2025-11-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0003_auto_20251122_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='batch_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Batch 1'), (2, 'Batch 2'), (3, 'Batch 3'), (4, 'Batch 4'), (5, 'Batch 5'), (6, 'Batch 6'), (7, 'Batch 7'), (8, 'Batch 8')], null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_room_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('rotaday', 'staff', 'clean_room', 'isolator', 'shift', 'batch_number')},
        ),
    ]
