# Generated by Django 3.2.25 on 2026-02-16 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_alter_operatorvalidation_operator'),
        ('rota', '0003_alter_assignment_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='isolator_section',
            field=models.ForeignKey(blank=True, help_text='Required for isolator assignments (e.g. Isolator 1 Left/Right).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='validation.isolatorsection'),
        ),
    ]
