# Generated by Django 3.2.25 on 2025-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0004_auto_20251126_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='location_type',
            field=models.CharField(choices=[('ROOM', 'Room (Supervisor)'), ('ISOLATOR', 'Isolator (Operative/Supervisor)')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('rotaday', 'staff')},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='batch_number',
        ),
    ]
