# Generated by Django 5.2.8 on 2026-04-29 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0004_assignment_isolator_section'),
        ('validation', '0003_auto_20260216_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('area_type', models.CharField(choices=[('MAL', 'MAL'), ('SUPPORT_ROOM', 'Support Room'), ('VISUAL_INSPECTION', 'Visual Inspection'), ('OVERLABELLING', 'Overlabelling'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('required_staff_am', models.PositiveSmallIntegerField(default=0)),
                ('required_staff_pm', models.PositiveSmallIntegerField(default=0)),
                ('requires_supervisor', models.BooleanField(default=False)),
                ('requires_validation', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='assignment',
            name='clean_room',
            field=models.ForeignKey(blank=True, help_text='Required for room and isolator assignments. Not required for work-area assignments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rota.cleanroom'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='isolator_section',
            field=models.ForeignKey(blank=True, help_text='Required for isolator assignments, e.g. Isolator 1 Left/Right.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='validation.isolatorsection'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='location_type',
            field=models.CharField(choices=[('ROOM', 'Room (Supervisor)'), ('ISOLATOR', 'Isolator (Operative/Supervisor)'), ('WORK_AREA', 'Work Area')], max_length=12),
        ),
        migrations.AddField(
            model_name='assignment',
            name='work_area',
            field=models.ForeignKey(blank=True, help_text='Required for work-area assignments, e.g. Clean MAL or Visual Inspection 1.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='rota.workarea'),
        ),
    ]
