# Generated by Django 3.2.25 on 2025-12-16 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rota', '0005_auto_20251210_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotaday',
            name='publish_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rotaday',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rotaday',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_rotadays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rotaday',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=12),
        ),
        migrations.CreateModel(
            name='RotaDayAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ASSIGNMENT_CREATED', 'Assignment created'), ('ASSIGNMENT_UPDATED', 'Assignment updated'), ('ASSIGNMENT_DELETED', 'Assignment deleted'), ('PUBLISHED', 'Published'), ('REPUBLISHED', 'Republished')], max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=255)),
                ('before_json', models.JSONField(blank=True, null=True)),
                ('after_json', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rota_audit_events', to=settings.AUTH_USER_MODEL)),
                ('rotaday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='rota.rotaday')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
