# Generated by Django 3.2.25 on 2026-02-16 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Isolator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IsolatorSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('isolator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='validation.isolator')),
            ],
            options={
                'ordering': ['isolator__sort_order', 'section'],
            },
        ),
        migrations.CreateModel(
            name='OperatorValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('IN_TRAINING', 'In Training'), ('RESTRICTED', 'Restricted'), ('SUSPENDED', 'Suspended')], default='VALID', max_length=20)),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('assessed_by', models.CharField(blank=True, max_length=120)),
                ('evidence_ref', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isolator_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator_validations', to='validation.isolatorsection')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='isolator_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['isolator_section', 'operator'],
            },
        ),
        migrations.AddIndex(
            model_name='operatorvalidation',
            index=models.Index(fields=['operator', 'isolator_section'], name='validation__operato_f19076_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorvalidation',
            index=models.Index(fields=['status', 'expires_on'], name='validation__status_116b0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operatorvalidation',
            unique_together={('operator', 'isolator_section')},
        ),
        migrations.AlterUniqueTogether(
            name='isolatorsection',
            unique_together={('isolator', 'section')},
        ),
    ]
