# Generated by Django 3.2.25 on 2026-02-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0003_alter_assignment_shift'),
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorvalidation',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='isolator_validations', to='rota.staffmember'),
        ),
    ]
