# Generated by Django 3.2.25 on 2026-02-16 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0004_assignment_isolator_section'),
        ('validation', '0002_alter_operatorvalidation_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isolatorsection',
            options={'ordering': ['isolator__clean_room__number', 'isolator__order', 'section']},
        ),
        migrations.AlterField(
            model_name='isolatorsection',
            name='isolator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='rota.isolator'),
        ),
        migrations.DeleteModel(
            name='Isolator',
        ),
    ]
